<?php

namespace Database\Factories;

use App\Models\Currency;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Currency>
 *
 * Generates currency catalog rows for billing and wallet foundation tests.
 */
class CurrencyFactory extends Factory
{
    public function definition(): array
    {
        return [
            'code' => fake()->unique()->currencyCode(),
            'name' => fake()->currencyCode().' Currency',
            'symbol' => null,
            'decimal_precision' => 2,
            'is_active' => true,
            'is_base' => false,
            'description' => 'Test currency generated by factory.',
            'metadata' => [
                'source' => 'factory',
            ],
        ];
    }

    public function usd(): static
    {
        return $this->state(fn (array $attributes) => [
            'code' => 'USD',
            'name' => 'US Dollar',
            'symbol' => '$',
        ]);
    }

    public function eur(): static
    {
        return $this->state(fn (array $attributes) => [
            'code' => 'EUR',
            'name' => 'Euro',
            'symbol' => 'EUR',
        ]);
    }

    public function uah(): static
    {
        return $this->state(fn (array $attributes) => [
            'code' => 'UAH',
            'name' => 'Ukrainian Hryvnia',
            'symbol' => 'UAH',
        ]);
    }

    public function pln(): static
    {
        return $this->state(fn (array $attributes) => [
            'code' => 'PLN',
            'name' => 'Polish Zloty',
            'symbol' => 'PLN',
        ]);
    }

    public function inactive(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_active' => false,
        ]);
    }

    public function base(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_base' => true,
        ]);
    }
}
